# Generated by Django 4.1.7 on 2023-08-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_courses_alter_student_stu_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classAddr',
            field=models.CharField(default='6', max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='classTime',
            field=models.CharField(default='3', max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(default=3, verbose_name='学分'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(default='2', max_length=32),
        ),
    ]
